#ifndef DIGGLER_SCRIPTING_LUA_API_CONTENT_REGISTRY_H
#define DIGGLER_SCRIPTING_LUA_API_CONTENT_REGISTRY_H

extern "C" {
#include "Registry.code.h"
}

#endif /* DIGGLER_SCRIPTING_LUA_API_CONTENT_REGISTRY_H */
